const APP_ERROR_STATUSES: Readonly<Record<string, number>> = {
  admin_identity_invalid: 403,
  admin_two_factor_invalid: 403,
  approval_required: 409,
  acquisition_owner_immutable: 409,
  acquisition_owner_not_found: 404,
  apps_script_http_error: 502,
  apps_script_invalid_response: 502,
  apps_script_not_configured: 503,
  apps_script_unavailable: 502,
  configuration_error: 503,
  consent_required: 409,
  daily_digest_consent_required: 409,
  delivery_consent_required: 409,
  delivery_identity_missing: 409,
  deck_storage_not_configured: 503,
  corrupt_data: 502,
  commission_actor_required: 409,
  commission_amount_locked: 409,
  commission_approval_required: 409,
  commission_payment_required: 409,
  commission_reason_required: 409,
  commission_void_reason_required: 409,
  forbidden: 403,
  identity_not_linked: 403,
  invalid_amount: 409,
  invalid_amounts: 409,
  invalid_commission_action: 400,
  invalid_commission_basis: 400,
  invalid_commission_rate: 400,
  invalid_effective_period: 409,
  invalid_content_type: 400,
  invalid_content_url: 400,
  invalid_content_visibility: 400,
  invalid_content_status: 400,
  invalid_delivery_channel: 400,
  invalid_digest_date: 400,
  invalid_prospect_channel: 400,
  invalid_prospect_status: 400,
  invalid_investment_ticket_range: 409,
  invalid_referrer_code: 400,
  invalid_referrer_email: 400,
  invalid_referrer_basis: 400,
  invalid_referrer_period: 409,
  invalid_referrer_status: 400,
  invalid_qualification_expiry: 409,
  invalid_request: 400,
  invalid_state: 400,
  invalid_transition: 409,
  line_push_failed: 502,
  lead_owner_attribution_conflict: 409,
  member_attribution_conflict: 409,
  not_found: 404,
  rate_limited: 429,
  replayed_envelope: 502,
  prospect_member_link_immutable: 409,
  prospect_member_link_required: 409,
  prospect_owner_conflict: 409,
  prospect_identity_immutable: 409,
  prospect_evidence_immutable: 409,
  public_content_approval_required: 409,
  investment_preferences_required: 409,
  referral_evidence_required: 409,
  referrer_not_effective: 409,
  referrer_not_found: 404,
  referrer_reason_required: 409,
  duplicate_referrer_code: 409,
  risk_acknowledgement_required: 409,
  seed_requires_empty_workbook: 409,
  state_amount_mismatch: 409,
  unknown_operation: 502,
  validation_error: 400,
};

export function appsScriptErrorStatus(code: string): number {
  const normalized = code.trim().toLowerCase();
  const exact = APP_ERROR_STATUSES[normalized];
  if (exact) return exact;
  if (normalized.endsWith('_not_found')) return 404;
  if (normalized.includes('forbidden') || normalized.includes('unauthorized')) return 403;
  if (normalized.includes('conflict')) return 409;
  if (normalized.includes('rate_limit')) return 429;
  if (normalized.startsWith('validation_')) return 400;
  return 502;
}
